on:
  push:
    branches:
      - main
      - dev
jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
      - name: Deploying to Dev
        uses: appleboy/ssh-action@v1.0.0
        if: github.ref == 'refs/heads/dev'
        with:
          host: ${{ secrets.DEV_SERVER }}
          username: ${{ secrets.DEV_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /root/apps/securelog-rsc-example
            git pull origin dev
            yarn install
            onboardbase run -c 'yarn build'
            cp -r dist/* /var/www/secure-example
            systemctl reload nginx
      - name: Deploying to prod
        uses: appleboy/ssh-action@v1.0.0
        if: github.ref == 'refs/heads/main'
        with:
          host: ${{ secrets.PROD_SERVER }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
           export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /root/apps/securelog-rsc-example
            git pull origin main
            yarn install
            onboardbase run -c 'yarn build'
            cp -r dist/* /var/www/secure-example
            systemctl reload nginx
